### ISSUE TITLE
Review the lateral perturbation comparison plot and data

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/perturbed-data-paper#159]
- [x] Shrink the height of the graph.
- [ ] Make sure we are plotting what we want.
- [ ] Maybe add the frequency spectrum.
- [x] Remove the commanded? (if we are not sure we have the correct commanded input)

Ton's comment:
> This plot looks pretty bad and may raise all sorts of questions.  Did the treadmill get even close to doing what we wanted?

**Comment by moorepants** [comment]
@spinningplates Are you sure that the file you provided with the commanded lateral position is the data that we used for trials 3-8? If you regenerated this with Simulink the random values would be different.

**Comment by moorepants** [comment]
Here is another graph of the lateral data:
![lateral-commanded-vs-actual](https://cloud.githubusercontent.com/assets/276007/6678932/65b7189c-cbfe-11e4-8da1-a9858f4b7362.png)

This shows the X deviation of all of the treadmill markers vs the commanded deviation.

There are similarities but the more I look at it I'm less convinced that this is the actual measurements that correspond to that lateral input.

Did we always use the same lateral input file? How often did you regenerate this data with Simulink?

**Comment by moorepants** [comment]
@spinningplates This is due tomorrow. Please let me know soon if you have any other knowledge of what may be going on here.

**Comment by moorepants** [comment]
I just removed the commanded for now since I haven't heard from you. If you think we are using the wrong file we can fix it. I also need to know if we are using the wrong file so I can remove it from the Zenodo download. Leaving this open till all that is addressed.

**Comment by spinningplates** [comment]
I grabbed the file directly from D-Flow that was in our testing protocol program and I've used the same signal for everything (even my own perturbation studies).  I recall that the treadmill has difficulties following the signal to the point where Motek had developed a new movement algorithm.  It made the movement smoother, but it still was never really able to follow the signal very well.  At the time, we didn't really consider it an issue as long as the treadmill movement was smooth, random, and that it sufficiently moved within the limits.

Also, running the Simulink several times will not produce different values.  The random number generator block requires an initial seed.  I've just rerun the Simulink several times and the signal is exactly the same.  This file hasn't changed since January of last year.  

I had mentioned that I didn't think the input and the output looked very good, and that it raises more questions than it answers.  Just having the measured value should be fine, as it was the actual motion of the treadmill.

**Comment by tvdbogert** [comment]
Yes, I agree that here we should only present the measured motion.

**Comment by moorepants** [comment]
> I grabbed the file directly from D-Flow that was in our testing protocol program and I've used the same signal for everything (even my own perturbation studies).

Ok, just wanted to check. Sounds good.

> At the time, we didn't really consider it an issue as long as the treadmill movement was smooth, random, and that it sufficiently moved within the limits.

Yes, this is still all that matters.

> The random number generator block requires an initial seed.

Good that you had set this.

> I had mentioned that I didn't think the input and the output looked very good, and that it raises more questions than it answers.

I know, still don't think it is "bad", it is just the truth, i.e. the treadmill doesn't follow the commanded signal well.

> Just having the measured value should be fine, as it was the actual motion of the treadmill. 

I changed it to that last night so we could submit. I'll close this issue now and leave the lateral perturbation data in the Zenodo download.

Thanks for the clarification.

**Comment by moorepants** [comment]
FYI: Last night I noticed the peerj due **hour** was this morning, i.e. we didn't have till the end of the day of the 17th. That's why I finished it up and submitted last night.
