### ISSUE TITLE
Note the issues associated with the TimeStamp column in the data.

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/perturbed-data-paper#170]
I just discovered this: https://github.com/csu-hmc/GaitAnalysisToolKit/issues/133 and it would be ideal if we could mention this in this paper.

**Comment by moorepants** [comment]
@tvdbogert @spinningplates Do you think I need to edit the paper to reflect this issue?

**Comment by tvdbogert** [comment]
Does it affect the results that were presented in the paper?  If not, you can just update the software so the problem does not happen again when people use the code.  I suspect that the graphs in the paper won't be affected by this problem.

**Comment by moorepants** [comment]
Yeh, the graphs would not change in any human perceptible way because I used a trial that had no marker drop out or time stack up issues. I'm just worried that the explanation of the TimeStamp column in the data is less than informative:

```latex
  \item[TimeStamp] The monotonically increasing computer clock time when D-Flow
    receives a frame from Cortex. These are recorded approximately at
    100~\si{\hertz} sampling rate and given in seconds.
```

I could add a sentence or so there when the proof comes through to mention the stack up issue. Maybe that is sufficient.

**Comment by tvdbogert** [comment]
The explanation of the TimeStamp column is technically still correct: "when D-Flow receives a frame".  I would add something like: because of buffering, we prefer derive sample times from the FrameNumber rather than TimeStamp".

The reader can then determine for themselves how much they want to trust the files that came from the Record module (which have no framenumber, right?).  We should not undermine the trust in the data at the proof stage, because the reviewers (if they ever read the paper again) would feel deceived because they never had that information when they evaluated the work.

A determined and creative user can get around these issues.  But it is scary that we did not even notice it for a long time, so a gentle warning in the TimeStamp explanation is needed.

**Comment by moorepants** [comment]
I'll mention the error to the editors, suggest they additional warning, and see what they say. They may need to send it back to the academic editor to get reviewer approval.
